[package]
name = "maze-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allegro = "0.0.43"
allegro_image = "0.0.43"
rand = "0.8.5"
